### ISSUE TITLE
WIN报错

### ISSUE THREAD

**Issue by verglas** [helingfeng/Docker-LNMP#5]
/var/run/docker.sock:/var/run/docker.sock:cached
写错了。前面

**Comment by luohuacc** [comment]
是哪写错了？

**Comment by luohuacc** [comment]
@verglas  是哪写错了， 我也遇到这个问题了

**Comment by luohuacc** [comment]
@helingfeng 您好， 我在编译php的时候出现了好多warning ， 请问下你在运行有没有出现？

**Comment by luohuacc** [comment]
@verglas  我的也出现这个问题了， 请问你是怎么解决的？

**Comment by verglas** [comment]
@luohuacc 你在.env里添加`COMPOSE_CONVERT_WINDOWS_PATHS=1`试试吧。
