### ISSUE TITLE
编译php时候出现warning，请问怎么解决？

### ISSUE THREAD

**Issue by luohuacc** [helingfeng/Docker-LNMP#6]
2. 编译 ext/intl 模块出现问题

	/usr/src/php/ext/intl/grapheme/grapheme_string.c: In function 'zif_grapheme_extract':
	/usr/src/php/ext/intl/grapheme/grapheme_string.c:868:14: warning: comparison of distinct pointer types lacks a cast
	    if ( pstr >= str_end ) {
	              ^~

	              
	In file included from /usr/src/php/ext/intl/grapheme/grapheme_string.c:24:0:
	/usr/src/php/ext/intl/grapheme/grapheme_string.c: At top level:
	/usr/src/php/ext/intl/grapheme/grapheme_util.h:38:14: warning: inline function 'grapheme_memrchr_grapheme' declared but never defined
	 inline void *grapheme_memrchr_grapheme(const void *s, int c, int32_t n);

	 In file included from /usr/src/php/ext/intl/grapheme/grapheme_util.c:24:0:
	/usr/src/php/ext/intl/grapheme/grapheme_util.h:38:14: warning: inline function 'grapheme_memrchr_grapheme' declared but never defined
	 inline void *grapheme_memrchr_grapheme(const void *s, int c, int32_t n);

	 /usr/src/php/ext/intl/timezone/timezone_methods.cpp: In function 'void zif_intltz_create_time_zone_id_enumeration(int, zval*, zval**, zval*, int)':
	/usr/src/php/ext/intl/timezone/timezone_methods.cpp:251:16: warning: 'int zend_get_parameters_ex(int, ...)' is deprecated [-Wdeprecated-declarations]
	   arg3isnull = zend_get_parameters_ex(3, &dummy, &dummy, &zvoffset)
	                ^~~~~~~~~~~~~~~~~~~~~~
	In file included from /usr/local/include/php/main/php.h:39:0,
	                 from /usr/src/php/ext/intl/timezone/../common/common_date.h:23,
	                 from /usr/src/php/ext/intl/timezone/timezone_methods.cpp:28:
	/usr/local/include/php/Zend/zend_API.h:241:40: note: declared here
	 ZEND_API ZEND_ATTRIBUTE_DEPRECATED int zend_get_parameters_ex(int param_count, ...);
	                                        ^~~~~~~~~~~~~~~~~~~~~~
	/usr/src/php/ext/intl/timezone/timezone_methods.cpp:251:67: warning: 'int zend_get_parameters_ex(int, ...)' is deprecated [-Wdeprecated-declarations]
	   arg3isnull = zend_get_parameters_ex(3, &dummy, &dummy, &zvoffset)
	                                                                   ^
	In file included from /usr/local/include/php/main/php.h:39:0,
	                 from /usr/src/php/ext/intl/timezone/../common/common_date.h:23,
	                 from /usr/src/php/ext/intl/timezone/timezone_methods.cpp:28:
	/usr/local/include/php/Zend/zend_API.h:241:40: note: declared here
	 ZEND_API ZEND_ATTRIBUTE_DEPRECATED int zend_get_parameters_ex(int param_count, ...);

	 /usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp: In function 'void zif_breakiter_set_text(int, zval*, zval**, zval*, int)':
/usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp:165:12: warning: 'int zend_get_parameters_ex(int, ...)' is deprecated [-Wdeprecated-declarations]
  int res = zend_get_parameters_ex(1, &textzv);
            ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/php/main/php.h:39:0,
                 from /usr/src/php/ext/intl/breakiterator/breakiterator_iterators.h:23,
                 from /usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp:24:
/usr/local/include/php/Zend/zend_API.h:241:40: note: declared here
 ZEND_API ZEND_ATTRIBUTE_DEPRECATED int zend_get_parameters_ex(int param_count, ...);
                                        ^~~~~~~~~~~~~~~~~~~~~~
/usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp:165:45: warning: 'int zend_get_parameters_ex(int, ...)' is deprecated [-Wdeprecated-declarations]
  int res = zend_get_parameters_ex(1, &textzv);
                                             ^
In file included from /usr/local/include/php/main/php.h:39:0,
                 from /usr/src/php/ext/intl/breakiterator/breakiterator_iterators.h:23,
                 from /usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp:24:
/usr/local/include/php/Zend/zend_API.h:241:40: note: declared here
 ZEND_API ZEND_ATTRIBUTE_DEPRECATED int zend_get_parameters_ex(int param_count, ...);
                                        ^~~~~~~~~~~~~~~~~~~~~~
/usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp: In function 'void zif_breakiter_next(int, zval*, zval**, zval*, int)':
/usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp:278:13: warning: 'int zend_get_parameters_ex(int, ...)' is deprecated [-Wdeprecated-declarations]
   int res = zend_get_parameters_ex(1, &arg);
             ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/php/main/php.h:39:0,
                 from /usr/src/php/ext/intl/breakiterator/breakiterator_iterators.h:23,
                 from /usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp:24:
/usr/local/include/php/Zend/zend_API.h:241:40: note: declared here
 ZEND_API ZEND_ATTRIBUTE_DEPRECATED int zend_get_parameters_ex(int param_count, ...);
                                        ^~~~~~~~~~~~~~~~~~~~~~
/usr/src/php/ext/intl/breakiterator/breakiterator_methods.cpp:278:43: warning: 'int zend_get_parameters_ex(int, ...)' is deprecated [-Wdeprecated-declarations]
   int res = zend_get_parameters_ex(1, &arg);

**Comment by helingfeng** [comment]
可以更换镜像源 source 尝试
