### ISSUE TITLE
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by a5653132** [helingfeng/Docker-LNMP#9]
你好， mac m1 遇到了这个问题，需要修改下什么地方？ 感谢

**Comment by helingfeng** [comment]
需要将镜像更新为：ARM64

例如：
https://hub.docker.com/_/mysql?tab=tags&page=1

<img width="816" alt="image" src="https://user-images.githubusercontent.com/4921878/182282093-1d3a815c-7fd8-47ba-bef8-6a0c9256573a.png">
